### ISSUE TITLE
Github Event: `issues` returns [object Object] sometimes

### ISSUE THREAD

**Issue by datitisev** [YappyBots/YappyGitHub#39]
> Reported by @AniLeo on Discord

![screenshot](https://images.discordapp.net/.eJwNycsNwyAMANBdGICvgZA1OkCFCIJICUbYOVXdvX3X9xHPusQuOvOkXanjpILrkMS4cquyIbar5nmSLHirzJxLv-tgUtYZD1sCA8lqG11yymkdDPgY4T9gtmDVq6xaB3Xkt4cg52ji-wP_5iTn.W8TD1ichzmk3MXy34Ca0gJebHi8)

```sh
[04/9/17 11:27:57]   debug: Got a `issues` from RPCS3/rpcs3 
```

**Comment by clienthax** [comment]
Pretty sure this is todo with editing or deleting a comment

**Comment by AniLeo** [comment]
![screenshot_547](https://cloud.githubusercontent.com/assets/10283761/24837561/bb3d2968-1d2e-11e7-96db-1d37cfd442c9.png)

Not deleted, and I don't think GitHub notifies for edited comments (?)

**Comment by datitisev** [comment]
Github does notify for edited comments, however, that usually causes an immense spam of messages, so I didn't add the event to Yappy.

**Comment by MarkehMe** [comment]
I get this when I tick a box in a checklist, change labels, or change milestones.

**Comment by datitisev** [comment]
@MarkehMe Thanks. I'll make sure the rewrite doesn't include this bug. 🙂

**Comment by isJuhn** [comment]
This is still an issue, just not as much as before.
![image](https://user-images.githubusercontent.com/26828095/36950038-a4fbdabc-1ff0-11e8-8d71-bab15b7613d8.png)

**Comment by datitisev** [comment]
Maybe fixed with https://github.com/YappyBots/YappyGithub/commit/d8130215cc382ee7d92c8748bba353404cdadff9

**Comment by isJuhn** [comment]
It might have helped, but it still happens. To reproduce, edit an issue.
![image](https://user-images.githubusercontent.com/26828095/37760268-7458b6fe-2db6-11e8-9580-d46cfeef4498.png)

**Comment by datitisev** [comment]
may have fixed it with https://github.com/YappyBots/YappyGithub/compare/d8130215cc38...28c349d

**Comment by isJuhn** [comment]
as of 5 minutes ago
![image](https://user-images.githubusercontent.com/26828095/37859801-f6339bda-2f19-11e8-981e-8d9501b69368.png)

**Comment by MSuih** [comment]
To clarify: It happens when the original/first post of an issue is modified, no messages are sent if replies are edited. And yes, rpcs3 is still getting the object object spam.

**Comment by isJuhn** [comment]
just a small update 
![image](https://user-images.githubusercontent.com/26828095/39445283-de368182-4cba-11e8-8004-65b370dad7ab.png)

**Comment by datitisev** [comment]
Hm, ok thanks. Will look into it when I have time.

**Comment by nitrohigito** [comment]
Please reopen, the issue still persists. @datitisev

**Comment by Megamouse** [comment]
So my understanding is that:
1. It happens when the original/first post of an **issue** is edited and **saved**.
2. It happens when the original/first post of a **pull request** is edited and **canceled**.

**Comment by datitisev** [comment]
@Megamouse What do you mean, _canceled_ ?

**Comment by Megamouse** [comment]
You have to edit the original comment in the pull request and at least change something (for example add a word) and then click cancel instead of "Update Comment"
![image](https://user-images.githubusercontent.com/23019877/58133866-63b5be00-7c25-11e9-899e-e5ed87d0115c.png)

**Comment by Megamouse** [comment]
Btw is there a simple way to test changes to the source code?
I've been trying to set up my own Yappy bot but I gave up since I had no build instructions

**Comment by datitisev** [comment]
@Megamouse Thanks for the explanation.

Regarding building, you'll need a MongoDB database. Then, copy `.env.example` into `.env` and fill in the required values (don't know which ones off the top of my head 🙄), and after installing the npm dependencies, running `node index` should work.

I haven't worked on it for a long time, so I don't remember everything, sorry.

**Comment by dsevillamartin** [comment]
No longer applies.
